import { ProductModelItem } from "@/shared/ui/ProductModelItem/ProductModelItem";

import { type ProductModel, type ProductSize, type ProductStyle, type PresetProduct } from "@/entities/product/types";

import img_24_1d from "@/shared/assets/images/png/hastings/Urban Standard · 24_ 1-Drawer 2.png";
import img_24_2d from "@/shared/assets/images/png/hastings/Urban Standard · 24_ 2-Drawer 2.png";
import img_28_1d from "@/shared/assets/images/png/hastings/Urban Standard · 28_ 1-Drawer 2.png";
import img_28_2d from "@/shared/assets/images/png/hastings/Urban Standard · 28_ 2-Drawer 2.png";
import img_32_1d from "@/shared/assets/images/png/hastings/Urban Standard · 32_ 1-Drawer 2.png";
import img_32_2d from "@/shared/assets/images/png/hastings/Urban Standard · 32_ 2-Drawer 2.png";
import img_34_1d from "@/shared/assets/images/png/hastings/Urban Standard · 34_ 1-Drawer 2.png";
import img_34_2d from "@/shared/assets/images/png/hastings/Urban Standard · 34_ 2-Drawer 2.png";
import img_36_1d from "@/shared/assets/images/png/hastings/Urban Standard · 36_ 1-Drawer 2.png";
import img_36_2d from "@/shared/assets/images/png/hastings/Urban Standard · 36_ 2-Drawer 2.png";
import img_42_1d from "@/shared/assets/images/png/hastings/Urban Standard · 42_ 1-Drawer 2.png";
import img_42_2d from "@/shared/assets/images/png/hastings/Urban Standard · 42_ 2-Drawer 2.png";
import img_42_1d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 42_ 1-Drawer_2 2.png";
import img_42_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 42_ 2-Drawer_2 2.png";
import img_46_1d from "@/shared/assets/images/png/hastings/Urban Standard · 46_ 1-Drawer 2.png";
import img_46_2d from "@/shared/assets/images/png/hastings/Urban Standard · 46_ 2-Drawer 2.png";
import img_48_1d from "@/shared/assets/images/png/hastings/Urban Standard · 48_ 1-Drawer 2.png";
import img_48_2d from "@/shared/assets/images/png/hastings/Urban Standard · 48_ 2-Drawer 2.png";
import img_48_1d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 48_ 1-Drawer_2 2.png";
import img_48_1d_v3 from "@/shared/assets/images/png/hastings/b97fb93d-b791-4acd-8baf-bd88a19b7eb0.png";
import img_48_1d_v4 from "@/shared/assets/images/png/hastings/b7e97e9d-1b51-4664-8f7a-507cc38099a6.png";
import img_48_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 48_ 2-Drawer_2 2.png";
import img_48_2d_v3 from "@/shared/assets/images/png/hastings/dbb363e6-8df5-46b3-9f05-a46f327c202d.png";
import img_51_2d from "@/shared/assets/images/png/hastings/f38fcc55-1e1d-4b55-b6fc-bbd57ce41005.png";
import img_55_1d from "@/shared/assets/images/png/hastings/c781ff9e-aec0-4919-ba2d-bacc9d3f6f60.png";
import img_55_2d from "@/shared/assets/images/png/hastings/Urban Standard · 55_ 2-Drawer 2.png";
import img_55_2d_double from "@/shared/assets/images/png/hastings/e8d8dab8-03e4-4218-86c3-a05a7ff67339.png";
import img_57_2d from "@/shared/assets/images/png/hastings/Urban Standard · 57_ 2-Drawer 2.png";
import img_59_1d from "@/shared/assets/images/png/hastings/Urban Standard · 59_ 1-Drawer 2.png";
import img_59_2d from "@/shared/assets/images/png/hastings/Urban Standard · 59_ 2-Drawer 2.png";
import img_59_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 59_ 2-Drawer_2 2.png";
import img_63_1d from "@/shared/assets/images/png/hastings/Urban Standard · 63_ 1-Drawer 2.png";
import img_63_1d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 63_ 1-Drawer_2 2.png";
import img_63_1d_v3 from "@/shared/assets/images/png/hastings/Urban Standard · 63_ 1-Drawer_3 2.png";
import img_63_2d from "@/shared/assets/images/png/hastings/Urban Standard · 63_ 2-Drawer 2.png";
import img_65_2d from "@/shared/assets/images/png/hastings/Urban Standard · 65_ 2-Drawer 2.png";
import img_67_2d from "@/shared/assets/images/png/hastings/Urban Standard · 67_ 2-Drawer 2.png";
import img_69_2d from "@/shared/assets/images/png/hastings/Urban Standard · 69_ 2-Drawer 2.png";
import img_69_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 69_ 2-Drawer_2 2.png";
import img_71_2d from "@/shared/assets/images/png/hastings/Urban Standard · 71_ 2-Drawer 2.png";
import img_73_1d from "@/shared/assets/images/png/hastings/Urban Standard · 73_ 1-Drawer 2.png";
import img_73_2d from "@/shared/assets/images/png/hastings/Urban Standard · 73_ 2-Drawer 2.png";
import img_75_2d from "@/shared/assets/images/png/hastings/Urban Standard · 75_ 2-Drawer 2.png";
import img_75_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 75_ 2-Drawer_2 2.png";
import img_75_2d_v3 from "@/shared/assets/images/png/hastings/Urban Standard · 75_ 2-Drawer_3 2.png";
import img_79_1d from "@/shared/assets/images/png/hastings/Urban Standard · 79_ 1-Drawer 2.png";
import img_83_1d from "@/shared/assets/images/png/hastings/Urban Standard · 83_ 1-Drawer 2.png";
import img_83_2d from "@/shared/assets/images/png/hastings/Urban Standard · 83_ 2-Drawer 2.png";
import img_83_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 83_ 2-Drawer_2 2.png";
import img_83_2d_v3 from "@/shared/assets/images/png/hastings/Urban Standard · 83_ 2-Drawer_3 2.png";
import img_87_1d from "@/shared/assets/images/png/hastings/Urban Standard · 87_ 1-Drawer 2.png";
import img_89_2d from "@/shared/assets/images/png/hastings/Urban Standard · 89_ 2-Drawer 2.png";
import img_89_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 89_ 2-Drawer_2 2.png";
import img_93_2d from "@/shared/assets/images/png/hastings/Urban Standard · 93_ 2-Drawer 2.png";
import img_95_1d from "@/shared/assets/images/png/hastings/Urban Standard · 95_ 1-Drawer 2.png";
import img_95_1d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 95_ 1-Drawer_2 2.png";
import img_95_2d from "@/shared/assets/images/png/hastings/Urban Standard · 95_ 2-Drawer 2.png";
import img_95_2d_v2 from "@/shared/assets/images/png/hastings/Urban Standard · 95_ 2-Drawer_2 2.png";
import img_97_1d from "@/shared/assets/images/png/hastings/Urban Standard · 97_ 1-Drawer 2.png";
import img_103_2d from "@/shared/assets/images/png/hastings/Urban Standard · 103_ 2-Drawer 2.png";

import s from "./ProductModelsGrid.module.scss";

function computeSize(title: string): ProductSize {
  const match = title.match(/(\d+)"/);

  const inches = match ? parseInt(match[1], 10) : 0;
  if (inches < 30) return "24_29";
  if (inches < 40) return "30_39";
  if (inches < 50) return "40_49";
  if (inches < 60) return "50_59";
  if (inches < 70) return "60_69";
  if (inches < 80) return "70_79";
  if (inches < 90) return "80_89";
  return "90_plus";
}

function computeStyles(presetProducts: PresetProduct[]): ProductStyle[] {
  const styles: ProductStyle[] = [];

  const hasDrawer1 = presetProducts.some((p) => p.Drawers === "1D");
  const hasDrawer2 = presetProducts.some((p) => p.Drawers === "2D");

  if (hasDrawer1) styles.push("1_drawer");
  if (hasDrawer2) styles.push("2_drawer");

  const sinkBases = presetProducts.filter((p) => p.name === "Sink-Base" && p.sinkType);
  if (sinkBases.length === 1) styles.push("single_basin");
  if (sinkBases.length >= 2) styles.push("double_basin");

  if (presetProducts.some((p) => p.name === "Open-Shelf")) styles.push("open_shelving");

  if (presetProducts.length >= 2) {
    const len = presetProducts.length;
    let isSymmetric = true;

    for (let i = 0; i < Math.floor(len / 2); i++) {
      const left = presetProducts[i];
      const right = presetProducts[len - 1 - i];
      if (left.name !== right.name || left.Width !== right.Width) {
        isSymmetric = false;
        break;
      }
    }
    if (!isSymmetric) styles.push("asymmetrical");
  }

  return styles;
}

function enrichProduct(raw: Omit<ProductModel, "size" | "style">): ProductModel {
  return {
    ...raw,
    size: computeSize(raw.title),
    style: computeStyles(raw.presetProducts),
  };
}

export const productMockData: ProductModel[] = (
  [
    {
      id: 1,
      img: img_24_1d,
      title: 'Urban Standard · 24" 1-Drawer',
      // desc: "60W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 2,
      img: img_24_2d,
      title: 'Urban Standard · 24" 2-Drawer',
      // desc: "60W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 3,
      img: img_28_1d,
      title: 'Urban Standard · 28" 1-Drawer',
      // desc: "70W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 4,
      img: img_28_2d,
      title: 'Urban Standard · 28" 2-Drawer',
      // desc: "70W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 5,
      img: img_32_1d,
      title: 'Urban Standard · 32" 1-Drawer',
      // desc: "80W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 6,
      img: img_32_2d,
      title: 'Urban Standard · 32" 2-Drawer',
      // desc: "80W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 7,
      img: img_34_1d,
      title: 'Urban Standard · 34" 1-Drawer',
      // desc: "Sink Base 60 + Side Cabinet 25 · 85W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 25,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 8,
      img: img_34_2d,
      title: 'Urban Standard · 34" 2-Drawer',
      // desc: "Side Cabinet 25 + Sink Base 60 · 85W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 25,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 9,
      img: img_36_1d,
      title: 'Urban Standard · 36" 1-Drawer',
      // desc: "90W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 10,
      img: img_36_2d,
      title: 'Urban Standard · 36" 2-Drawer',
      // desc: "90W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 11,
      img: img_42_1d,
      title: 'Urban Standard · 42" 1-Drawer',
      // desc: "105W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 12,
      img: img_42_2d,
      title: 'Urban Standard · 42" 2-Drawer',
      // desc: "105W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 13,
      img: img_42_1d_v2,
      title: 'Urban Standard · 42" 1-Drawer',
      // desc: "Sink Base 70 + Side Cabinet 35 · 105W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 14,
      img: img_42_2d_v2,
      title: 'Urban Standard · 42" 2-Drawer',
      // desc: "Sink Base 70 + Side Cabinet 35 · 105W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 15,
      img: img_46_1d,
      title: 'Urban Standard · 46" 1-Drawer',
      // desc: "Sink Base 80 + Side Cabinet 35 · 115W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 16,
      img: img_46_2d,
      title: 'Urban Standard · 46" 2-Drawer',
      // desc: "Sink Base 80 + Side Cabinet 35 · 115W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 17,
      img: img_48_1d,
      title: 'Urban Standard · 48" 1-Drawer',
      // desc: "Sink Base 70 + Side Cabinet 50 · 120W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 18,
      img: img_48_2d,
      title: 'Urban Standard · 48" 2-Drawer',
      // desc: "Sink Base 70 + Side Cabinet 50 · 120W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 19,
      img: img_48_1d_v2,
      title: 'Urban Standard · 48" 1-Drawer',
      // desc: "Sink Base 60 + Sink Base 60 · 120W × 51D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 20,
      img: img_48_2d_v2,
      title: 'Urban Standard · 48" 2-Drawer',
      // desc: "Sink Base 60 + Sink Base 60 · 120W × 51D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 55,
      img: img_48_2d_v3,
      title: 'Urban Standard · 48" 2-Drawer',
      // desc: "Sink Base 120 (2-Drawer) · 120W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 120,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 56,
      img: img_48_1d_v3,
      title: 'Urban Standard · 48" 1-Drawer',
      // desc: "Sink Base 60 (1-Drawer) + Sink Cabinet 60 (1-Drawer) · 120W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 60,
      img: img_48_1d_v4,
      title: 'Urban Standard · 48" 1-Drawer',
      // desc: "Sink Base 70 (1-Drawer) + Sink Cabinet 50 (1-Drawer) · 120W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 57,
      img: img_51_2d,
      title: 'Urban Standard · 51" 2-Drawer',
      // desc: "Open Shelf 50 + Sink Base 80 (2-Drawer) · 130W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 50,
          Depth: 50.5,
          Height: 56,
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 58,
      img: img_55_1d,
      title: 'Urban Standard · 55" 1-Drawer',
      // desc: "Sink Base 105 (1-Drawer) + Sink Cabinet 35 (1-Drawer) · 140W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 21,
      img: img_55_2d,
      title: 'Urban Standard · 55" 2-Drawer',
      // desc: "Sink Base 70 (2-Drawer) + Open Shelf 35 + Side Cabinet 35 (2-Drawer) · 140W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 35,
          Depth: 50.5,
          Height: 56,
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 59,
      img: img_55_2d_double,
      title: 'Urban Standard · 55" 2-Drawer Double',
      // desc: "Sink Base 70 (2-Drawer) + Sink Base 70 (2-Drawer) · 140W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 22,
      img: img_57_2d,
      title: 'Urban Standard · 57" 2-Drawer',
      // desc: "Open Shelf 35 + Side Cabinet 50 (2-Drawer) + Sink Base 60 (2-Drawer) · 145W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 35,
          Depth: 50.5,
          Height: 56,
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 23,
      img: img_59_1d,
      title: 'Urban Standard · 59" 1-Drawer',
      // desc: "Side Cabinet 70 (1-Drawer) + Sink Base 80 (1-Drawer) · 150W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 24,
      img: img_59_2d,
      title: 'Urban Standard · 59" 2-Drawer',
      // desc: "Sink Base 90 (2-Drawer) + Side Cabinet 60 (2-Drawer) · 150W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 25,
      img: img_59_2d_v2,
      title: 'Urban Standard · 59" 2-Drawer',
      // desc: "Sink Base 70 (2-Drawer) + Side Cabinet 80 (2-Drawer) · 150W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 26,
      img: img_63_1d,
      title: 'Urban Standard · 63" 1-Drawer',
      // desc: "Sink Base 90 (1-Drawer) + Open Shelf 35 + Side Cabinet 35 (1-Drawer) · 160W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 35,
          Depth: 50.5,
          Height: 53,
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 27,
      img: img_63_1d_v2,
      title: 'Urban Standard · 63" 1-Drawer',
      // desc: "Side Cabinet 35 (1-Drawer) + Sink Base 90 (1-Drawer) + Side Cabinet 35 (1-Drawer) · 160W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 28,
      img: img_63_1d_v3,
      title: 'Urban Standard · 63" 1-Drawer',
      // desc: "Sink Base 80 (1-Drawer) + Side Cabinet 80 (1-Drawer) · 160W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 29,
      img: img_63_2d,
      title: 'Urban Standard · 63" 2-Drawer',
      // desc: "Sink Base 80 (2-Drawer) + Sink Base 80 (2-Drawer) · 160W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 30,
      img: img_65_2d,
      title: 'Urban Standard · 65" 2-Drawer',
      // desc: "Side Cabinet 60 (2-Drawer) + Sink Base 105 (2-Drawer) · 165W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 31,
      img: img_67_2d,
      title: 'Urban Standard · 67" 2-Drawer',
      // desc: "Side Cabinet 50 (2-Drawer) + Sink Base 70 (2-Drawer) + Open Shelf 50 · 170W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 50,
          Depth: 50.5,
          Height: 56,
        },
      ],
    },
    {
      id: 32,
      img: img_69_2d,
      title: 'Urban Standard · 69" 2-Drawer',
      // desc: "Sink Base 105 (2-Drawer) + Side Cabinet 70 (2-Drawer) · 175W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 33,
      img: img_69_2d_v2,
      title: 'Urban Standard · 69" 2-Drawer',
      // desc: "Sink Base 80 (2-Drawer) + Side Cabinet 60 (2-Drawer) + Side Cabinet 35 (2-Drawer) · 175W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 34,
      img: img_71_2d,
      title: 'Urban Standard · 71" 2-Drawer',
      // desc: "Sink Base 90 (2-Drawer) + Sink Base 90 (2-Drawer) · 180W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 35,
      img: img_73_1d,
      title: 'Urban Standard · 73" 1-Drawer',
      // desc: "Side Cabinet 60 (1-Drawer) + Open Shelf 35 + Sink Base 90 (1-Drawer) · 185W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 35,
          Depth: 50.5,
          Height: 53,
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 36,
      img: img_73_2d,
      title: 'Urban Standard · 73" 2-Drawer',
      // desc: "Sink Base 90 (2-Drawer) + Side Cabinet 60 (2-Drawer) + Side Cabinet 35 (2-Drawer) · 185W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 37,
      img: img_75_2d,
      title: 'Urban Standard · 75" 2-Drawer',
      // desc: "Sink Base 120 (2-Drawer) + Side Cabinet 70 (2-Drawer) · 190W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 120,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 38,
      img: img_75_2d_v2,
      title: 'Urban Standard · 75" 2-Drawer',
      // desc: "Side Cabinet 50 (2-Drawer) + Sink Base 90 (2-Drawer) + Side Cabinet 50 (2-Drawer) · 190W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 39,
      img: img_75_2d_v3,
      title: 'Urban Standard · 75" 2-Drawer',
      // desc: "Sink Base 105 (2-Drawer) + Side Cabinet 50 (2-Drawer) + Open Shelf 35 · 190W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 35,
          Depth: 50.5,
          Height: 56,
        },
      ],
    },
    {
      id: 40,
      img: img_79_1d,
      title: 'Urban Standard · 79" 1-Drawer',
      // desc: "Sink Base 70 (1-Drawer) + Side Cabinet 60 (1-Drawer) + Sink Base 70 (1-Drawer) · 200W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 41,
      img: img_83_1d,
      title: 'Urban Standard · 83" 1-Drawer',
      // desc: "Sink Base 90 (1-Drawer) + Side Cabinet 60 (1-Drawer) + Side Cabinet 60 (1-Drawer) · 210W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 42,
      img: img_83_2d,
      title: 'Urban Standard · 83" 2-Drawer',
      // desc: "Sink Base 70 (2-Drawer) + Side Cabinet 70 (2-Drawer) + Sink Base 70 (2-Drawer) · 210W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 43,
      img: img_83_2d_v2,
      title: 'Urban Standard · 83" 2-Drawer',
      // desc: "Sink Base 105 (2-Drawer) + Sink Base 105 (2-Drawer) · 210W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 44,
      img: img_83_2d_v3,
      title: 'Urban Standard · 83" 2-Drawer',
      // desc: "Sink Base 80 (2-Drawer) + Side Cabinet 50 (2-Drawer) + Sink Base 80 (2-Drawer) · 210W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 45,
      img: img_87_1d,
      title: 'Urban Standard · 87" 1-Drawer',
      // desc: "Sink Base 80 (1-Drawer) + Open Shelf 60 + Sink Base 80 (1-Drawer) · 220W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 60,
          Depth: 50.5,
          Height: 53,
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 46,
      img: img_89_2d,
      title: 'Urban Standard · 89" 2-Drawer',
      // desc: "Side Cabinet 105 (2-Drawer) + Sink Base 120 (2-Drawer) · 225W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 120,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 47,
      img: img_89_2d_v2,
      title: 'Urban Standard · 89" 2-Drawer',
      // desc: "Side Cabinet 60 (2-Drawer) + Sink Base 105 (2-Drawer) + Side Cabinet 60 (2-Drawer) · 225W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 48,
      img: img_93_2d,
      title: 'Urban Standard · 93" 2-Drawer',
      // desc: "Side Cabinet 80 (2-Drawer) + Side Cabinet 50 (2-Drawer) + Sink Base 105 (2-Drawer) · 235W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 49,
      img: img_95_1d,
      title: 'Urban Standard · 95" 1-Drawer',
      // desc: "Sink Base 90 (1-Drawer) + Side Cabinet 60 (1-Drawer) + Sink Base 90 (1-Drawer) · 240W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 90,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 50,
      img: img_95_1d_v2,
      title: 'Urban Standard · 95" 1-Drawer',
      // desc: "Sink Base 80 (1-Drawer) + Side Cabinet 80 (1-Drawer) + Sink Base 80 (1-Drawer) · 240W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 51,
      img: img_95_2d,
      title: 'Urban Standard · 95" 2-Drawer',
      // desc: "Sink Base 120 (2-Drawer) + Sink Base 120 (2-Drawer) · 240W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 120,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 120,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
    {
      id: 52,
      img: img_95_2d_v2,
      title: 'Urban Standard · 95" 2-Drawer',
      // desc: "Side Cabinet 60 (2-Drawer) + Sink Base 120 (2-Drawer) + Side Cabinet 60 (2-Drawer) · 240W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 120,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 60,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
      ],
    },
    {
      id: 53,
      img: img_97_1d,
      title: 'Urban Standard · 97" 1-Drawer',
      // desc: "Side Cabinet 70 (1-Drawer) + Sink Base 105 (1-Drawer) + Open Shelf 35 + Side Cabinet 35 (1-Drawer) · 245W × 50.5D × 53H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 70,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 105,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 35,
          Depth: 50.5,
          Height: 53,
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 35,
          Depth: 50.5,
          Height: 53,
          Drawers: "1D",
        },
      ],
    },
    {
      id: 54,
      img: img_103_2d,
      title: 'Urban Standard · 103" 2-Drawer',
      // desc: "Sink Base 80 (2-Drawer) + Open Shelf 25 + Side Cabinet 50 (2-Drawer) + Open Shelf 25 + Sink Base 80 (2-Drawer) · 260W × 50.5D × 56H cm",
      isProductModel: true,
      // price: "Price on request",
      presetProducts: [
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 25,
          Depth: 50.5,
          Height: 56,
        },
        {
          name: "Sink-Cabinet",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 50,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
        },
        {
          name: "Open-Shelf",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Width: 25,
          Depth: 50.5,
          Height: 56,
        },
        {
          name: "Sink-Base",
          CabinetColor: "Pulpis Chiaro TKH",
          CountertopColor: "Cacao Orinoco FF MT",
          Handle: "handle_urban_topcut",
          Width: 80,
          Depth: 50.5,
          Height: 56,
          Drawers: "2D",
          sinkType: "Top_Tekorlux_Rectangular",
        },
      ],
    },
  ] as Omit<ProductModel, "size" | "style">[]
).map(enrichProduct);

interface ProductModelsGridI {
  data?: ProductModel[];
  createModelBtn?: React.ReactNode;
  handleAddPreset: (presetProducts?: PresetProduct[], presetId?: number) => void;
  handleCustomizePreset: (presetProducts?: PresetProduct[]) => void;
  activePresetId?: number | null;
}

export const ProductModelsGrid: React.FC<ProductModelsGridI> = ({
  data,
  createModelBtn,
  handleAddPreset,
  handleCustomizePreset,
  activePresetId,
}) => {
  const items = data ?? productMockData;

  return (
    <div className={s.optionsGridWrapper}>
      <div className={s.optionsGrid}>
        {createModelBtn}

        {items.map((i) => {
          return (
            <ProductModelItem
              key={i.id}
              id={i.id}
              title={i.title}
              img={i.img}
              desc={i.desc}
              price={i.price}
              isProductModel={true}
              presetProducts={i.presetProducts}
              onSelect={handleAddPreset}
              onCustomize={handleCustomizePreset}
              isActive={activePresetId === i.id}
            />
          );
        })}
      </div>
    </div>
  );
};
