import {
  INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS,
  type InteractiveConfiguratorTutorialStep,
} from "./types";
import { INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS } from "./targets";

export const INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES = {
  prebuiltModel: "/prebuilt/model",
  customCabinetType: "/custom/cabinet-builder?accordion=cabinet-type",
  customCabinetStyle: "/custom/cabinet-builder?accordion=cabinet-style",
} as const;

export const INTERACTIVE_CONFIGURATOR_TUTORIAL_STEPS = [
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.intro,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.page,
    placement: "center",
    title: "Take the Interactive Walkthrough",
    description:
      "We'll walk through the two main configuration paths and highlight key configuration and navigational aspects of the modular configure experience. Let's get started!",
    primaryLabel: "Next",
    secondaryLabel: "Skip",
    secondaryAction: "skip",
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.gettingStarted,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.modelModeSwitcher,
    placement: "left",
    title: "How to Get Started",
    description:
      "There are two primary configuration paths:\n- Pre-built mode: Where you can customize your design from pre-made solutions\n- Custom mode: Where you build your custom, tailored design with full design control",
    progressLabel: "1 of 3",
    primaryLabel: "Next",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.prebuiltModel,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.prebuiltMode,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.prebuiltModelsGrid,
    placement: "left",
    title: "Pre-Built Mode",
    description:
      "- Scroll our selection of pre-made models\n- Sort by size and style\nPro Tip: Click 'customize' on any model to import a pre-built design into custom mode for full cabinet design control",
    progressLabel: "2 of 3",
    primaryLabel: "Next",
    secondaryLabel: "Back",
    secondaryAction: "back",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.prebuiltModel,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.prebuiltDetails,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.prebuiltNextButton,
    placement: "top",
    title: "Pre-Built Mode",
    description:
      "From here, personalize your solution details: select your cabinet colors, countertop details and accessorize your design until it's perfect.",
    progressLabel: "3 of 3",
    primaryLabel: "Next",
    secondaryLabel: "Back",
    secondaryAction: "back",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.prebuiltModel,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.customMode,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.createYourOwnMode,
    placement: "left",
    title: "Custom Mode",
    description:
      "Want even more design control? Then custom mode is for you!\nBuild your own custom, tailored solution with full design control: our easy-to-use cabinet builder allows you to add, remove, reposition cabinets and more.",
    primaryLabel: "Next",
    secondaryLabel: "Back",
    secondaryAction: "back",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.prebuiltModel,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.customCabinetType,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.customCabinetType,
    placement: "left",
    title: "Custom Mode",
    description: "Cabinet Type\nChoose your cabinet type to get started",
    progressLabel: "1 of 4",
    primaryLabel: "Next",
    secondaryLabel: "Back",
    secondaryAction: "back",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.customCabinetType,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.customCabinetStyle,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.customCabinetStyle,
    placement: "left",
    title: "Custom Mode",
    description: "Cabinet Style\nPick your cabinet style to suit your visual and storage needs.",
    progressLabel: "2 of 4",
    primaryLabel: "Next",
    secondaryLabel: "Back",
    secondaryAction: "back",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.customCabinetStyle,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.customSizingHandle,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.customSizingHandle,
    placement: "left",
    title: "Custom Mode",
    description: "Sizing & Handle\nPick your cabinet size and handle style.",
    progressLabel: "3 of 4",
    primaryLabel: "Next",
    secondaryLabel: "Back",
    secondaryAction: "back",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.customCabinetStyle,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  {
    id: INTERACTIVE_CONFIGURATOR_TUTORIAL_STEP_IDS.customPlaceCabinet,
    target: INTERACTIVE_CONFIGURATOR_TUTORIAL_TARGETS.customPlaceCabinet,
    placement: "left",
    title: "Custom Mode",
    description: "Place Your Cabinet\nTap on a '+' to insert your selected cabinet",
    progressLabel: "4 of 4",
    primaryLabel: "Get Started",
    secondaryLabel: "Back",
    secondaryAction: "back",
    route: INTERACTIVE_CONFIGURATOR_TUTORIAL_ROUTES.customCabinetStyle,
    spotlightPadding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
] as const satisfies readonly InteractiveConfiguratorTutorialStep[];
